version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
    ports:
      - '33061:3306'

  opencart:
    image: 'bitnami/opencart:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=33061
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_HOST=localhost
      - ALLOW_EMPTY_PASSWORD=yes
      - VIRTUAL_HOST=oc.kalimtab.com
    labels:
      kompose.service.type: nodeport
    volumes:
      - 'opencart_data:/bitnami'
    depends_on:
      - mariadb
    expose:
      - 80

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local

networks:
  default:
    external:
      name: nginx-proxy